### ISSUE TITLE
Cannot create a second integration

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1116] opened 2017-10-19 09:16 UTC
When creating a second integration the following happens:

![image](https://user-images.githubusercontent.com/99080/31763484-b0b0e8f4-b4be-11e7-821f-609acbc77e86.png)

**Comment by rhuss** [comment] 2017-10-19 10:03
This happens also when you delete an integration and try to create a new one.

**Comment by gashcrumb** [comment] 2017-10-19 12:22
At what point exactly?  Like right when you click the 'Create Integration' button?

**Comment by gashcrumb** [comment] 2017-10-19 12:36
So far I can't reproduce this.

**Comment by rhuss** [comment] 2017-10-19 13:13
Just cant reproduce it either. Let me try it again later with the latest version ...

**Comment by gashcrumb** [comment] 2017-10-19 13:17
Interesting, maybe just clear your cache before testing just to be on the safe side perhaps?

**Comment by gashcrumb** [comment] 2017-10-23 15:14
I think this must have been a fluke, let's close this for now, can be re-opened if there's reproducible circumstances that show the problem consistently.

**Closed by gashcrumb** 2017-10-23 15:14 UTC
Labels: Priority - Blocking, TP2
