### ISSUE TITLE
New step on integration is always added as first one

### ISSUE THREAD

**Issue by lvydra** [syndesisio/syndesis-ui#841] opened 2017-08-28 13:55 UTC
If you trying to add step on certain position, step is added as first one.

**Comment by gashcrumb** [comment] 2017-08-28 14:02
This should have been fixed in this commit -> https://github.com/syndesisio/syndesis-ui/commit/a9cd7694c68a32c15c32819693b9984ac26b09ff and I can't reproduce it locally, maybe you're not testing against the latest commit?

**Comment by gashcrumb** [comment] 2017-08-28 14:22
BTW, we definitely need an about page with the date the image was created -> https://github.com/syndesisio/syndesis-ui/issues/844

**Comment by gashcrumb** [comment] 2017-08-28 16:56
Also steps to reproduce if I'm missing something would be good :-)

**Comment by lvydra** [comment] 2017-08-28 18:03
Just trying to add step on any position different then first/top one create it on first/top position.

**Comment by gashcrumb** [comment] 2017-08-28 19:04
Yeah, staging seems to be out of date, but the builds haven't errored out at all.  @jimmidyson @rhuss any ideas?

**Comment by zregvart** [comment] 2017-08-29 07:42
I've kicked of a new build of `master` branch, let's see if staging gets updated.

**Comment by zregvart** [comment] 2017-08-29 09:44
The changes in syndesisio/syndesis-rest#535 modified the database schema, now `syndesis-rest` is not starting.

**Comment by gashcrumb** [comment] 2017-09-01 13:29
I still can't reproduce this locally or on staging, @lvydra have you tried perhaps clearing your browser cache?

**Comment by lvydra** [comment] 2017-09-01 13:49
It is OK already.

**Comment by gashcrumb** [comment] 2017-09-01 14:26
Ok, cool, thanks!

**Closed by gashcrumb** 2017-09-01 14:26 UTC
Labels: bug
